### ISSUE TITLE
The build fails with an error.

### ISSUE THREAD

**Issue by blackcross86** [fedora-java/jurand#11]
```c++
g++ -g -std=c++2a -Isrc -Wall -Wextra -Wpedantic -MM -MG -MMD -MP -MF target/dependencies/jurand.mk -MT target/object_files/jurand.o -o /dev/null src/jurand.cpp
g++ -g -std=c++2a -Isrc -Wall -Wextra -Wpedantic -MMD -MP -MF target/dependencies/jurand.mk -MT target/object_files/jurand.o -c -o target/object_files/jurand.o src/jurand.cpp
In file included from src/jurand.cpp:8:
src/java_symbols.hpp: In function 'std::string java_symbols::handle_file(const Path_origin_entry&, const Parameters&)':
src/java_symbols.hpp:633:41: error: 'osyncstream' is not a member of 'std'; did you mean 'ostringstream'?
  633 |                 auto osyncstream = std::osyncstream(std::cout);
      |                                         ^~~~~~~~~~~
      |                                         ostringstream
src/java_symbols.hpp:653:22: error: 'osyncstream' is not a member of 'std'; did you mean 'ostringstream'?
  653 |                 std::osyncstream(std::clog) << "Removing symbols from file " << path.native() << "\n";
      |                      ^~~~~~~~~~~
      |                      ostringstream
make: *** [Makefile:21: target/object_files/jurand.o] Error 1
```

gcc version 13.2.0

**Comment by mkoncek** [comment]
This is really strange, GCC 12 and newer should have `osyncstream` included. What operating system are you using? This looks like something is wrong with your system header files.

**Comment by blackcross86** [comment]
> This is really strange, GCC 12 and newer should have `osyncstream` included. What operating system are you using? This looks like something is wrong with your system header files.

Rosa Linux. yes we need to look at what is the problem with gcc

**Comment by mkoncek** [comment]
Since the error message is not about include file `<syncstream>` not being found but about the class itself. Looks like it is either not present at all or is behind some `#ifdef`.

**Comment by fedya** [comment]
it's funny but issue lays in --with-default-libstdcxx-abi=gcc4-compatible in gcc configure options
looks like gcc bug

**Comment by mkoncek** [comment]
If it helps you, there is a Rust version of this project in the branch `rust`. AFAIK it behaves identically, at least on success.

**Comment by blackcross86** [comment]
> If it helps you, there is a Rust version of this project in the branch `rust`. AFAIK it behaves identically, at least on success.

thank you.Let's know what jurand is on rust.Bug with gcc fixed

**Comment by mkoncek** [comment]
@blackcross86 Did you resolve your issue?

**Comment by blackcross86** [comment]
> @blackcross86 Did you resolve your issue?

yes, the problem can be closed.Thanks
