### ISSUE TITLE
Jurand does not handle non-ASCII names

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/jurand#4]
I have the following file:
```
@č class ř{}
```
I am trying to remove `@č` annotation.
`jurand -a -n č -i ř.java` - does nothing

**Comment by mkoncek** [comment]
https://github.com/fedora-java/jurand/commit/74db230c17367c773b12f36f9760ac3d03a6653d Makes this possible but it is a bit hacky. Nevertheless it should work on 8-bit encodings and UTF-8.
