### ISSUE TITLE
RFE: Strict mode

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/jurand#7]
Implement a strict mode.

In strict mode Jurand should fail if:
- at least one of specified matchers did not match anything
- at least one of specified source files/directories was not modified
- `-a` is given, but not annotation was removed

For example see [this commit in guava package](https://src.fedoraproject.org/rpms/guava/c/c2625cdbc3a21a3156482c77d1cc79c67b018c4b)
Regex matcher `com[.]google[.]errorprone[.]annotation[.]` matches nothing in Guava sources.
Yet the tool does not point this out.
Another matche `com[.]google[.]errorprone[.]annotations[.]` was added to fix that.

Pull request demonstrates that matcher could be removed: https://src.fedoraproject.org/rpms/jurand/pull-request/3

**Comment by mkoncek** [comment]
I am unsure whether to go with only the verbose `--strict` option or also a short `-s`.

**Comment by mizdebsk** [comment]
Other options have short variants, so for consistency I would add `-s` too.
